### ISSUE TITLE
Grid 的 .offset1 的 margin-left 不对

### ISSUE THREAD

**Issue by Miaonster** [ddouble/bsie#14]
Hi again～

最近在 IE6 上用 Grid，比如给第一个 .span3 加上 .offset1 之后，位置还是没有变化。

看了下代码，发现有这样一句 [https://github.com/ddouble/bsie/blob/master/js/bootstrap-ie.js#L124](https://github.com/ddouble/bsie/blob/master/js/bootstrap-ie.js#L124)，所有的 `[class*=span]:first-child` 都会被加上一个 class `span-first-child`，也就是加上了一个 `margin-left: 10px`。于是 .offset\* 就不再起作用了。

我猜，这一句是为了解决 IE6 下的 "double margin" 的问题，如果是这样的话，我等下会创建一个 pull-request 来 fix 这个问题。

**Comment by hightman** [comment]
@Witcher42 有没有考虑将 bsie 里的 less 文件升级为 bootstrap 2.3.2 呀；我曾经尝试过失败了，编译都成问题……
似乎 2.2 <-> 2.3 之间那些 npm 安装的方式都变了。

**Comment by hightman** [comment]
hi, 还有一个问题，你们的更新只更新了 less 文件，而最终编译后调用的 css 却没有更新。。。

**Comment by Miaonster** [comment]
Hi，@hightman，升级到 2.3.2 对我来说还是要颇费一番功夫的。我对 IE6 所知不多，只能说尝试尝试，而目前也就是碰到问题挑挑 bug……╮(╯▽╰)╭

另外，我等下编译成 css 之后提一个 pull-request
